# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
# See also
# http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11/30925448#30925448
# to allow C++11, though we are not yet building with -std=c++11

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is our version already, and clang-X.Y does not exist.
#- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - ls /usr/local
  - ls /usr/local/bin
  - export PATH=/usr/local/bin:/usr/bin:${PATH}
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-get update
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      ;
    fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - software-properties-common
    - george-edison55/precise-backports
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - valgrind
    - cmake

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

script: 
  - mkdir build || true
  - mkdir build/safaia_framework || true
  - cd build/safaia_framework
  - cmake ../../
  - make

notifications:
  email: false

sudo: true