language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

matrix:
  exclude:
    - os: linux
      compiler: clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - export PATH=/usr/local/bin:/usr/bin:${PATH}
  - ./travis-before.sh
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export PATH="/tmp/cmake/bin:${PATH}"; fi
  - env | sort

script: ./travis.sh

after_success:
  - if [ "$UNIT_TEST" = "true" ] && [ "${TRAVIS_OS_NAME}" = "linux" ]; then coveralls --gcov /usr/bin/gcov-4.9 --exclude lib --exclude tests --gcov-options '\-lp'; fi
  - if [ "$UNIT_TEST" = "true" ] && [ "${TRAVIS_OS_NAME}" = "osx" ]; then coveralls --exclude lib --exclude tests --gcov-options '\-lp'; fi

env:
  matrix:
    - UNIT_TEST=true
    - UNIT_TEST=false

notifications:
  email: false

sudo: false