# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
# See also
# http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11/30925448#30925448
# to allow C++11, though we are not yet building with -std=c++11

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - ls /usr/local
  - ls /usr/local/bin
  - export PATH=/usr/local/bin:/usr/bin:${PATH}
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.sh -O /tmp/cmake_install.sh
      && mkdir -p /tmp/cmake
      && sh /tmp/cmake_install.sh --exclude-subdir --prefix=/tmp/cmake
      && export PATH="/tmp/cmake/bin:${PATH}"
      && cmake --version
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      ;
    fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: linux
      compiler: clang

script: 
  - mkdir build || true
  - mkdir build/safaia_framework || true
  - cd build/safaia_framework
  - cmake ../../
  - make

notifications:
  email: false

sudo: false